site_name: Josep Coin Biot
site_url: https://2zwfchnrnw-cyber.github.io/Web-de-prova-Josep-Coin-/

theme:
  name: material

docs_dir: 'md'
site_dir: 'docs'

nav:
  - Apuntes: Els meus apunts.md
  - Diapositivas: Presentació.md